export enum Language {
  Arabic = 'ar',
  Chinese = 'zh',
  Dutch = 'nl',
  English = 'en',
  French = 'fr',
  German = 'de',
  Greek = 'el',
  Hebrew = 'he',
  Hindi = 'hi',
  Italian = 'it',
  Japanese = 'ja',
  Malayalam = 'ml',
  Marathi = 'mr',
  Norwegian = 'no',
  Portuguese = 'pt',
  Romanian = 'ro',
  Russian = 'ru',
  Spanish = 'es',
  Swedish = 'sv',
  Tamil = 'ta',
  Telugu = 'te',
  Ukrainian = 'uk',
}
